# Copyright (c) 2026 kogeler
# SPDX-License-Identifier: MIT

"""Build GitHub dependency-submission manifests from all committed hash locks."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path
from urllib.parse import quote

DEFAULT_ROOT = Path(__file__).resolve().parents[2]
LOCK_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)\s+\\$")
LOCK_HASH = re.compile(r"^--hash=sha256:([0-9a-f]{64})(?:\s+\\)?$")
DIRECT_REQUIREMENT = re.compile(
    r"^([A-Za-z0-9][A-Za-z0-9._-]*)"
    r"(?:\[[A-Za-z0-9._-]+(?:,[A-Za-z0-9._-]+)*\])?==([^\s;]+)$"
)


class SnapshotError(ValueError):
    """Raised when dependency inputs cannot produce an exact snapshot."""


def _normalize_package(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).casefold()


def _load_project(path: Path) -> dict[str, object]:
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as err:
        raise SnapshotError(f"cannot read {path}: {err}") from err
    project = document.get("project")
    if not isinstance(project, dict):
        raise SnapshotError(f"{path}: missing [project] table")
    return project


def _direct_requirements(requirements: object, *, source: str) -> dict[str, str]:
    if not isinstance(requirements, list) or not all(
        isinstance(requirement, str) for requirement in requirements
    ):
        raise SnapshotError(f"{source}: dependencies must be an array of strings")

    direct: dict[str, str] = {}
    for requirement in requirements:
        match = DIRECT_REQUIREMENT.fullmatch(requirement)
        if match is None:
            raise SnapshotError(f"{source}: dependency must be one exact PyPI pin: {requirement}")
        name = _normalize_package(match.group(1))
        if name in direct:
            raise SnapshotError(f"{source}: duplicate direct dependency: {name}")
        direct[name] = match.group(2)
    return direct


def _read_lock(path: Path, *, allow_empty: bool) -> dict[str, str]:
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as err:
        raise SnapshotError(f"cannot read {path}: {err}") from err
    if "autogenerated by pip-compile" not in content:
        raise SnapshotError(f"{path}: missing pip-compile generated header")

    pins: dict[str, str] = {}
    current_name: str | None = None
    current_version = ""
    current_hashes: set[str] = set()

    def finish_pin() -> None:
        nonlocal current_name, current_version, current_hashes
        if current_name is None:
            return
        if not current_hashes:
            raise SnapshotError(f"{path}: {current_name}=={current_version} has no SHA-256 hash")
        pins[current_name] = current_version
        current_name = None
        current_version = ""
        current_hashes = set()

    for line_number, line in enumerate(content.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if line[:1].isspace():
            hash_match = LOCK_HASH.fullmatch(stripped)
            if hash_match is None or current_name is None:
                raise SnapshotError(f"{path}:{line_number}: unsupported lock continuation")
            digest = hash_match.group(1)
            if digest in current_hashes:
                raise SnapshotError(f"{path}:{line_number}: duplicate SHA-256 hash")
            current_hashes.add(digest)
            continue

        pin_match = LOCK_PIN.fullmatch(line)
        if pin_match is None:
            raise SnapshotError(f"{path}:{line_number}: unsupported lock entry")
        finish_pin()
        current_name = _normalize_package(pin_match.group(1))
        current_version = pin_match.group(2)
        if current_name in pins:
            raise SnapshotError(f"{path}:{line_number}: duplicate package pin: {current_name}")

    finish_pin()
    if not pins and not allow_empty:
        raise SnapshotError(f"{path}: lock contains no package pins")
    return pins


def _resolved_dependencies(
    path: Path,
    *,
    direct: dict[str, str],
    scope: str,
) -> dict[str, dict[str, str]]:
    pins = _read_lock(path, allow_empty=not direct)
    missing = sorted(set(direct) - set(pins))
    if missing:
        raise SnapshotError(f"{path}: direct dependencies missing from lock: {', '.join(missing)}")
    mismatched = sorted(name for name, version in direct.items() if pins[name] != version)
    if mismatched:
        details = ", ".join(
            f"{name}=={direct[name]} (lock has {pins[name]})" for name in mismatched
        )
        raise SnapshotError(f"{path}: direct dependency versions differ: {details}")

    return {
        name: {
            "package_url": f"pkg:pypi/{quote(name, safe='')}@{quote(version, safe='')}",
            "relationship": "direct" if name in direct else "indirect",
            "scope": scope,
        }
        for name, version in sorted(pins.items())
    }


def build_manifests(root: Path) -> dict[str, dict[str, object]]:
    project = _load_project(root / "pyproject.toml")
    runtime = _direct_requirements(project.get("dependencies"), source="pyproject.toml")
    if runtime:
        raise SnapshotError(
            "pyproject.toml: runtime dependencies require a dedicated reviewed lock policy"
        )
    optional = project.get("optional-dependencies")
    expected_groups = {"dev", "test", "package", "docs"}
    if not isinstance(optional, dict) or set(optional) != expected_groups:
        raise SnapshotError(
            "pyproject.toml: expected exactly the dev, test, package, and docs optional groups"
        )
    direct_by_group = {
        group: _direct_requirements(
            optional[group],
            source=f"pyproject.toml [project.optional-dependencies].{group}",
        )
        for group in expected_groups
    }
    definitions = (
        ("requirements-dev.txt", runtime | direct_by_group["dev"], "development"),
        ("requirements-test.txt", runtime | direct_by_group["test"], "development"),
        ("requirements-package.txt", runtime | direct_by_group["package"], "development"),
        ("requirements-docs.txt", runtime | direct_by_group["docs"], "development"),
    )
    return {
        name: {
            "name": name,
            "file": {"source_location": name},
            "resolved": _resolved_dependencies(root / name, direct=direct, scope=scope),
        }
        for name, direct, scope in definitions
    }


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--output", type=Path, required=True)
    return parser


def _run(args: argparse.Namespace) -> None:
    payload = {"manifests": build_manifests(args.root)}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    try:
        args.output.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
    except OSError as err:
        raise SnapshotError(f"cannot write {args.output}: {err}") from err
    counts = {name: len(manifest["resolved"]) for name, manifest in payload["manifests"].items()}
    print(
        "Dependency snapshot generated: "
        + ", ".join(f"{name}={count}" for name, count in counts.items())
    )


def main() -> int:
    try:
        _run(_build_parser().parse_args())
    except SnapshotError as err:
        print(f"dependency snapshot error: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
