# Copyright (c) 2026 kogeler
# SPDX-License-Identifier: MIT

"""Build GitHub dependency-submission manifests from all committed hash locks.

Each lock is cross-checked against the exact direct pins of its same-stem
requirements input.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path
from urllib.parse import quote

DEFAULT_ROOT = Path(__file__).resolve().parents[2]
LOCK_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)\s+\\$")
LOCK_HASH = re.compile(r"^--hash=sha256:([0-9a-f]{64})(?:\s+\\)?$")
DIRECT_REQUIREMENT = re.compile(
    r"^([A-Za-z0-9][A-Za-z0-9._-]*)"
    r"(?:\[[A-Za-z0-9._-]+(?:,[A-Za-z0-9._-]+)*\])?==([^\s;]+)$"
)
INPUT_COMMENT = re.compile(r"(?:^|\s)#.*$")
AUDIENCES = ("dev", "test", "package", "docs")


class SnapshotError(ValueError):
    """Raised when dependency inputs cannot produce an exact snapshot."""


def _normalize_package(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).casefold()


def _validate_project(path: Path) -> None:
    """Reject package metadata that duplicates or adds dependency versions."""
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as err:
        raise SnapshotError(f"cannot read {path}: {err}") from err
    project = document.get("project")
    if not isinstance(project, dict):
        raise SnapshotError(f"{path}: missing [project] table")
    if project.get("dependencies") != []:
        raise SnapshotError(
            "pyproject.toml: runtime dependencies require a dedicated reviewed lock policy"
        )
    if "optional-dependencies" in project:
        raise SnapshotError(
            "pyproject.toml: tool dependency versions must exist only in requirements inputs"
        )


def _input_requirements(path: Path) -> dict[str, str]:
    """Return exact direct pins from one independent requirements input."""
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as err:
        raise SnapshotError(f"cannot read {path}: {err}") from err

    direct: dict[str, str] = {}
    for line_number, line in enumerate(content.splitlines(), start=1):
        requirement = INPUT_COMMENT.sub("", line).strip()
        if not requirement:
            continue
        if requirement.startswith("-"):
            raise SnapshotError(
                f"{path}:{line_number}: an independent input cannot include files or options"
            )
        match = DIRECT_REQUIREMENT.fullmatch(requirement)
        if match is None:
            raise SnapshotError(f"{path}:{line_number}: dependency must be one exact PyPI pin")
        name = _normalize_package(match.group(1))
        if name in direct:
            raise SnapshotError(f"{path}: duplicate direct dependency: {name}")
        direct[name] = match.group(2)
    if not direct:
        raise SnapshotError(f"{path}: input contains no direct dependency pins")
    return direct


def _read_lock(path: Path) -> dict[str, str]:
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as err:
        raise SnapshotError(f"cannot read {path}: {err}") from err
    if "autogenerated by pip-compile" not in content:
        raise SnapshotError(f"{path}: missing pip-compile generated header")

    pins: dict[str, str] = {}
    current_name: str | None = None
    current_version = ""
    current_hashes: set[str] = set()

    def finish_pin() -> None:
        nonlocal current_name, current_version, current_hashes
        if current_name is None:
            return
        if not current_hashes:
            raise SnapshotError(f"{path}: {current_name}=={current_version} has no SHA-256 hash")
        pins[current_name] = current_version
        current_name = None
        current_version = ""
        current_hashes = set()

    for line_number, line in enumerate(content.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if line[:1].isspace():
            hash_match = LOCK_HASH.fullmatch(stripped)
            if hash_match is None or current_name is None:
                raise SnapshotError(f"{path}:{line_number}: unsupported lock continuation")
            digest = hash_match.group(1)
            if digest in current_hashes:
                raise SnapshotError(f"{path}:{line_number}: duplicate SHA-256 hash")
            current_hashes.add(digest)
            continue

        pin_match = LOCK_PIN.fullmatch(line)
        if pin_match is None:
            raise SnapshotError(f"{path}:{line_number}: unsupported lock entry")
        finish_pin()
        current_name = _normalize_package(pin_match.group(1))
        current_version = pin_match.group(2)
        if current_name in pins:
            raise SnapshotError(f"{path}:{line_number}: duplicate package pin: {current_name}")

    finish_pin()
    if not pins:
        raise SnapshotError(f"{path}: lock contains no package pins")
    return pins


def _resolved_dependencies(
    path: Path,
    *,
    direct: dict[str, str],
    scope: str,
) -> dict[str, dict[str, str]]:
    pins = _read_lock(path)
    missing = sorted(set(direct) - set(pins))
    if missing:
        raise SnapshotError(f"{path}: direct dependencies missing from lock: {', '.join(missing)}")
    mismatched = sorted(name for name, version in direct.items() if pins[name] != version)
    if mismatched:
        details = ", ".join(
            f"{name}=={direct[name]} (lock has {pins[name]})" for name in mismatched
        )
        raise SnapshotError(f"{path}: direct dependency versions differ: {details}")

    return {
        name: {
            "package_url": f"pkg:pypi/{quote(name, safe='')}@{quote(version, safe='')}",
            "relationship": "direct" if name in direct else "indirect",
            "scope": scope,
        }
        for name, version in sorted(pins.items())
    }


def build_manifests(root: Path) -> dict[str, dict[str, object]]:
    _validate_project(root / "pyproject.toml")
    manifests: dict[str, dict[str, object]] = {}
    for audience in AUDIENCES:
        name = f"requirements-{audience}.txt"
        direct = _input_requirements(root / f"requirements-{audience}.in")
        manifests[name] = {
            "name": name,
            "file": {"source_location": name},
            "resolved": _resolved_dependencies(root / name, direct=direct, scope="development"),
        }
    return manifests


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--output", type=Path, required=True)
    return parser


def _run(args: argparse.Namespace) -> None:
    payload = {"manifests": build_manifests(args.root)}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    try:
        args.output.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
    except OSError as err:
        raise SnapshotError(f"cannot write {args.output}: {err}") from err
    counts = {name: len(manifest["resolved"]) for name, manifest in payload["manifests"].items()}
    print(
        "Dependency snapshot generated: "
        + ", ".join(f"{name}={count}" for name, count in counts.items())
    )


def main() -> int:
    try:
        _run(_build_parser().parse_args())
    except SnapshotError as err:
        print(f"dependency snapshot error: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
